# Generated by Django 4.2.7 on 2023-12-07 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_answer_author_remove_answer_is_correct_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='user',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='user',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='user',
            new_name='profile',
        ),
    ]
